#!/usr/bin/perl

use PGPLOT;
use POSIX qw(log10);

my $dev = "?" unless defined $dev; 

pgbegin(0,$dev,1,1);  # Open plot device 

pgscf(1);             # Set character font
pgslw(2);             # Set line width
pgsch(1);           # Set character height
pgsfs(2);


pgenv(1.5,3,-1,1.2,0,-2);
pgsch(1.0);
pgbox('BCNSTL',1,0,'BCSTVNL',1,2);
pgsch(1.0);
pglabel("Temperature (K)","Speed (km/sec)","");

PlotGas(46,"Carbon Dioxide");
PlotGas(32,"Oxygen, Nitrogen");
PlotGas(18,"Water, Methane, Ammonia");
PlotGas(2,"Hydrogen");
PlotGas(4,"Heluim");

PlotPlanet(4.3,443,"Mercury",1,3);
PlotPlanet(10.4,733,"Venus",1.4,4);
PlotPlanet(11.2,288,"Earth",1,4);
PlotPlanet(2.38,250,"Moon",1,3);
PlotPlanet(5.0,223,"Mars",1,4);
PlotPlanet(59.5,120,"Jupiter",1,2);
PlotPlanet(35.6,89,"Saturn",1,2);
PlotPlanet(21.3,53,"Uranus",0.85,2);
PlotPlanet(23.3,54,"Neptune",0.9,2);
PlotPlanet(1.1,40,"Pluto",1.4,3);
PlotPlanet(2.64,89,"Titan",1,4);
PlotPlanet(1.452,54,"Triton",1,3);

pgsch(1);           # Set character height


pgend;

exit; #go home drink beer

sub PlotPlanet {
    
    my $vesc = shift;
    my $T = shift;
    my $label = shift;
    my $flag = shift;
    my $color = shift;
    
    my $logT = log10($T);
    my $logV = log10(0.11 * $vesc);
    #    my $logV = log10(0.167 * $vesc);
    
    my $newx = $logT * 1.0;
    my $newy = log10(0.11 * $vesc * 0.82 * $flag);
    
    pgsci($color);
    pgsch(1.5);
    pgpt(1,$logT,$logV,-10);
    pgsch(1);
    pgsci(1);
    pgptxt($newx,$newy,0,0.5,$label);
    
}

sub PlotGas {
    
    my $mass = shift;
    my $label = shift;
    
    $v1 = log10 ( 157 / 1000 * sqrt ( 1 / $mass ));
    $v1000 = log10 ( 157 / 1000 * sqrt ( 1000 / $mass ));
    
    my $newx = 2.95;
    my $newy = log10 ( 0.84 * 157 / 1000 * sqrt ( 1000 / $mass ));
    
    pgsls(2);
    pgmove(0,$v1);
    pgdraw(3,$v1000);
    pgsls(1);
    
    pgscf(3);
    pgsch(0.8);
    pgptxt($newx,$newy,15,1,$label);
    pgsch(1);
    pgscf(1);
    
}
